[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient @ ^2.8
  https://github.com/HyakErik/LD2410S.git
extra_scripts = post:copy_firmware.py
build_flags =
  -DCORE_DEBUG_LEVEL=3
